name: shift_space
description: "A Nasa Hackaton Project from Shift Space Team"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^2.8.0
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^14.7.2
  collection: ^1.18.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  freezed: ^3.0.6
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
